// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.EthereumPrice
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("price")]
        public double? Price { get; set; }

        [JsonProperty("marketCap")]
        public long? MarketCap { get; set; }

        [JsonProperty("volume24h")]
        public long? Volume24H { get; set; }

        [JsonProperty("change24h")]
        public double? Change24H { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset? LastUpdated { get; set; }

        [JsonProperty("high24h")]
        public double? High24H { get; set; }

        [JsonProperty("low24h")]
        public double? Low24H { get; set; }

        [JsonProperty("changeDirection")]
        public string ChangeDirection { get; set; }

        [JsonProperty("formatted")]
        public Formatted Formatted { get; set; }
    }

    public partial class Formatted
    {
        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("marketCap")]
        public string MarketCap { get; set; }

        [JsonProperty("volume")]
        public string Volume { get; set; }

        [JsonProperty("priceWords")]
        public string PriceWords { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
